FROM python:3.12-slim

# Copie as dependências do host para o contêiner (main.py e requirements.txt)
# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app
# Copie as dependências do host para o contêiner
COPY requirements.txt requirements.txt
# Instale as dependências
RUN pip install -r requirements.txt
# Copie o arquivo principal do host para o contêiner
COPY main.py main.py
# Comando para rodar a aplicação
CMD ["python", "main.py"]
