FROM mysql

# Copie o arquivo 'codigo.sql' do host para o diretório docker-entrypoint-initdb.d/
# Copie o arquivo 'codigo.sql' do host para o diretório docker-entrypoint-initdb.d/
COPY codigo.sql /docker-entrypoint-initdb.d/
